package NQTPREP;

// public class RABGESSUM(
//     int n1 = 2;
//     int n2 = 9;
//     //to store on 
//     int sum= 0;
//     for(int i = 1;i<=r;i++){
//         sum+=i;

//     }
//     System.out.println(+sum);

// )
public class Main {
    public static void main(String args[]) {
      int l = 2, r = 7;
      int sum = 0;
      for (int i = l; i <= r; i++) {
        sum += i;
      }
      System.out.print("The sum of the numbers in the given range is "+sum);
    }
  }